import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, Coffee, MapPin, Mic2 } from 'lucide-react';
import { useEvents } from './useEvents';
import { NotFound } from './InfoPages';

export function EventPage() {
  const { id } = useParams();
  const { events } = useEvents();
  const event = events.find(entry => entry.id === id);
  if (!event) return <NotFound />;
  return <section className="container page-section"><Link to="/#events" className="back-link"><ArrowLeft size={16} aria-hidden="true" /> Все хакатоны</Link><div className="detail-heading"><div><span className="eyebrow">{event.eyebrow}</span><h1 tabIndex={-1}>{event.title}</h1><p className="lead muted">{event.description}</p></div><div className="detail-date"><strong>{event.day}</strong><span>{event.month} 2026</span></div></div><div className="detail-layout"><div className="prose"><h2>От идеи до защиты</h2><p>{event.detail}</p><h2>Как участвовать</h2><ol>{event.steps.map(step => <li key={step}>{step}</li>)}</ol><p>Каждый участник регистрируется отдельно. Если у вас есть команда, укажите одинаковое название. Если команды нет — выбери соответствующий пункт в заявке.</p><h2>{event.hasChallenge ? 'Пробное задание и рейтинг' : 'Как показать работу с ИИ'}</h2>{event.hasChallenge ? <><p>До 15 октября исследуй учебные данные о студенческом кафе, построй классификатор и загрузи CSV-предсказания. На сайте появится твой F1-балл. Это подготовительная задача; основной кейс 18 октября будет отдельным.</p><Link className="button button-secondary" to="/challenge">Открыть пробное задание <ArrowUpRight size={18} aria-hidden="true" /></Link></> : <><p>На защите расскажи, какие инструменты использовал, как формулировал задачи и передавал контекст, что проверил сам и что изменил после ошибок. Достаточно нескольких конкретных примеров.</p><p>Покажи работающий пользовательский сценарий и честно обозначь ограничения. ИИ можно применять при создании продукта; встраивать нейросеть в сам продукт необязательно.</p></>}<h2>В течение дня</h2><div className="day-flow">{['Знакомство и задача', 'Работа над решением', 'Кофе-брейк', 'Защита перед жюри'].map((step, index) => <div key={step}><span className="mono">0{index + 1}</span>{step}</div>)}</div><p className="small muted">Точное время начала, продолжительность и состав жюри объявим в канале. Критерии основного хакатона сообщим до начала работы над кейсом.</p></div><aside className="event-sidebar"><span className="eyebrow">СОХРАНИ ДАТУ</span><h2>{event.day} {event.month}</h2><p>Регистрация до {event.deadlineLabel},<br />23:59 МСК.</p><Link to={`/register?event=${event.id}`} className="button full-width">{event.open === false ? 'Проверить регистрацию' : 'Участвовать'}<ArrowUpRight size={18} aria-hidden="true" /></Link><hr /><p><MapPin size={18} aria-hidden="true" /> Общежитие №2 ГУАП</p><p className="small muted">Санкт-Петербург, Передовиков, 13, корп. 1</p><p><Coffee size={18} aria-hidden="true" /> Кофе-брейк</p><p><Mic2 size={18} aria-hidden="true" /> Жюри и обратная связь</p><hr /><Link className="text-link" to={`/prepare?track=${event.id === 'start' ? 'ml' : 'vibe'}`}>Материалы для подготовки ↗</Link></aside></div></section>;
}
