import { useSearchParams, Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight, BookOpen, Check } from 'lucide-react';
import { materials } from './materials';
import { NotFound } from './InfoPages';

export function Prepare() {
  const [params, setParams] = useSearchParams();
  const track = ['ml', 'vibe'].includes(params.get('track') || '') ? params.get('track')! : 'all';
  const visible = materials.filter(material => track === 'all' || material.track === 'all' || material.track === track);
  return <section className="container page-section"><span className="eyebrow">БАЗА ЗНАНИЙ / ПЕРЕД СТАРТОМ</span><div className="page-heading"><h1 tabIndex={-1}>Немного подготовки.<br /><span className="accent">Гораздо больше уверенности.</span></h1><p className="lead muted">Короткие инструкции, с которыми проще<br />прийти к своему первому результату.</p></div><div className="filter-bar" aria-label="Направление материалов">{[['all', 'Все материалы'], ['ml', 'Campus ML'], ['vibe', 'Вайбкодинг']].map(([value, label]) => <button key={value} className={track === value ? 'filter active' : 'filter'} aria-pressed={track === value} onClick={() => setParams(value === 'all' ? {} : { track: value })}>{label}</button>)}</div><div className="material-list">{visible.map((material, index) => <Link className="material-row" to={`/prepare/${material.slug}`} key={material.slug}><span className="mono muted">0{index + 1}</span><div><span className="eyebrow">{material.track === 'ml' ? 'МАШИННОЕ ОБУЧЕНИЕ' : material.track === 'vibe' ? 'РАЗРАБОТКА С ИИ' : 'ДЛЯ ОБОИХ ХАКАТОНОВ'}</span><h2>{material.title}</h2><p>{material.description}</p></div><span className="material-time"><BookOpen size={15} aria-hidden="true" />{material.duration}</span><ArrowUpRight size={24} aria-hidden="true" /></Link>)}</div><div className="notice preparation-note"><div><h2>Лучше один маленький проект, чем десять прочитанных гайдов.</h2><p>Проверь знания на пробном задании Campus ML: данные, базовая модель и рейтинг уже на сайте.</p></div><Link to="/challenge" className="button button-secondary">К заданию <ArrowUpRight size={18} aria-hidden="true" /></Link></div></section>;
}

export function MaterialPage() {
  const { slug } = useParams();
  const material = materials.find(entry => entry.slug === slug);
  if (!material) return <NotFound />;
  return <article className="container page-section article-page"><Link to="/prepare" className="back-link"><ArrowLeft size={16} aria-hidden="true" /> Все материалы</Link><span className="eyebrow">ПОДГОТОВКА / {material.duration}</span><h1 tabIndex={-1}>{material.title}</h1><p className="lead muted">{material.description}</p><div className="article-layout"><nav aria-label="Содержание статьи">{material.sections.map((section, index) => <a key={section.title} href={`#part-${index}`}>{String(index + 1).padStart(2, '0')} / {section.title}</a>)}</nav><div className="prose">{material.sections.map((section, index) => <section id={`part-${index}`} key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}{section.code && <pre tabIndex={0}><code>{section.code}</code></pre>}{section.checklist && <ul className="checklist">{section.checklist.map(check => <li key={check}><Check size={18} aria-hidden="true" />{check}</li>)}</ul>}</section>)}{material.links && <section><h2>Первоисточники</h2><ul>{material.links.map(link => <li key={link.url}><a href={link.url} target="_blank" rel="noreferrer">{link.title} ↗</a></li>)}</ul></section>}<Link className="button" to={material.track === 'vibe' ? '/register?event=vibe' : '/challenge'}>{material.track === 'vibe' ? 'Записаться на вайбкодинг' : 'Попробовать на практике'}<ArrowUpRight size={18} aria-hidden="true" /></Link></div></div></article>;
}
